TutorMediaBD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'homepage'),
    path('tuition/<slug:book_slug>/', views.home, name = 'tuition_wise_category'),
    path('tuitions/', include('tuitions.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('singup/', views.UserRegistrationView.as_view(), name = 'singup'),
    path('active/<uid64>/<token>/', views.activate, name = 'activate'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('pass_change/', views.pass_change, name='passchange'),
]

tuitions/urls.py
from django.urls import path, include
from . views import DetailTuitionView,ApplyTutionView,ContactUsView, view_comments, Review,apply_tuition
urlpatterns = [
    path('tuition/<int:id>', DetailTuitionView.as_view(), name='tuition_details'),
    path('tuition_request/<int:id>/', ApplyTutionView.as_view(), name='tuition_request'),
    path('contact_us/', ContactUsView.as_view(), name='contact_us'),
    path('view/<int:id>', view_comments, name='view_details'),
    path('apply_tuition/', apply_tuition, name='apply_tuition'),
    path('review/<int:id>', Review.as_view(), name='review'),
]

tuitions/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tution(models.Model):
    classes = models.CharField(max_length = 100)
    slug = models.SlugField(max_length = 100, unique = True, blank=True, null=True)

    def __str__(self):
        return self.classes


class TutionDetails(models.Model):
    tuition = models.ForeignKey(Tution, on_delete = models.CASCADE, blank=True, null=True)
    teacher_name = models.CharField(max_length = 50)
    subject_name = models.CharField(max_length = 50)
    location = models.CharField(max_length = 200)
    tuition_days = models.CharField(max_length = 50,blank=True, null=True)
    salary = models.CharField(max_length = 50)
    is_available = models.BooleanField(default=True)
    image = models.ImageField(upload_to = 'tuition_app/media/uploads/', blank=True, null=True)

    def __str__(self) :
        return f"Subject name: {self.subject_name}, Tuition : {self.tuition.classes}"



class TuitionApplication(models.Model):
    APPLICANT_STATUS = (
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    )

    applicant = models.ForeignKey(User, on_delete=models.CASCADE)
    tuition = models.ForeignKey(TutionDetails, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=APPLICANT_STATUS, default='pending')

    def __str__(self):
        return f"{self.applicant.username} - {self.status}"


class ContactUs(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    phone_no = models.CharField(max_length=13)
    comments = models.TextField()

    def __str__(self):
        return self.fullname




class Comment(models.Model):
    car = models.ForeignKey(TutionDetails, on_delete = models.CASCADE, related_name = 'comments')
    name = models.CharField(max_length = 30)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"Comment by {self.name}"

tuitions/forms.py
from django import forms
from .models import Tution, TutionDetails,TuitionApplication, ContactUs, Comment

class CategoryForm(forms.ModelForm):
    class Meta: 
        model = Tution
        fields = '__all__'

class AddBookForm(forms.ModelForm):
    class Meta: 
        model = TutionDetails
        fields = '__all__'


class TuitionApplicationForm(forms.ModelForm):
    class Meta:
        model = TuitionApplication
        fields = ['applicant']


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta: 
        model = Comment
        fields = ['name', 'email', 'body']


    

tuitions/views.py
from django.views.generic import DetailView
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TutionDetails, TuitionApplication
from django.shortcuts import render, get_object_or_404
from .forms import CommentForm, ContactForm
from .models import Comment, ContactUs
from . import forms
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string


def send_apply_email(user, subject, template):
        message = render_to_string(template, {
            'user' : user,
        })
        send_email = EmailMultiAlternatives(subject, '', to=[user.email])
        send_email.attach_alternative(message, "text/html")
        send_email.send()



class DetailTuitionView(DetailView):
    model = TutionDetails
    template_name = 'tuition_details.html'
    pk_url_kwarg = 'id'
    context_object_name = 'tuition_details'

    def post(self, request, *args, **kwargs):
        comment_form = forms.CommentForm(data = self.request.POST)
        car  = self.get_object()
        if comment_form.is_valid():
            new_comment = comment_form.save(commit = False)
            new_comment.car = car
            new_comment.save()
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        car = self.object
        comments = car.comments.all()

        
        comment_form = forms.CommentForm()

        context ['comments'] = comments
        context ['comment_form'] = comment_form
        return context
    


class ApplyTutionView(LoginRequiredMixin, View):
    def get(self, request, id):
        tuition_detail = get_object_or_404(TutionDetails, pk=id)

        if tuition_detail.is_available:
            # Check if the user has already applied for this tuition
            existing_application = TuitionApplication.objects.filter(
                applicant=request.user,
                tuition=tuition_detail,
            ).first()

            if not existing_application:
                # Create a new application
                application = TuitionApplication(
                    applicant=request.user,
                    tuition=tuition_detail,
                    status='pending',
                )
                application.save()
                send_apply_email(self.request.user, "Apply Message", "apply_email.html")

                messages.success(request, 'Application submitted successfully.')
            else:
                messages.warning(request, 'You have already applied for this tuition.')

        else:
            messages.warning(request, 'This tuition is not available.')

        return redirect('apply_tuition')


def apply_tuition(request):
    return render(request, 'applyed_tuition.html')


class Review(DetailView):
    model = TutionDetails
    template_name = "review_form.html"
    pk_url_kwarg = 'id'
    context_object_name = 'review'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(data = self.request.POST)
        car  = self.get_object()
        if comment_form.is_valid():
            new_comment = comment_form.save(commit = False)
            new_comment.car = car
            new_comment.save()
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        car = self.object
        comments = car.comments.all()
        comment_form = CommentForm()
        context ['comments'] = comments
        context ['comment_form'] = comment_form
        return context



class ContactUsView(View):
    template_name = 'contact_page.html'
    success_url = reverse_lazy('contact_us')

    def get(self, request, *args, **kwargs):
        form = ContactForm()
        return render(request, self.template_name, {'form': form})
    
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contact_us')
        
        return render(request, self.template_name, {'form': form})
    




def view_comments(request, book_id):
    book = get_object_or_404(TutionDetails, pk=book_id)
    comments = Comment.objects.filter(car=book)

    if request.method == 'POST' and request.user.is_authenticated:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.car = book
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'comments.html', {'comment_form': comment_form, 'comments': comments, 'user': request.user})

tuitions/templates/apply_email.html
<h2>Hello {{user.first_name}} {{user.last_name}}</h2>

<h4>Your Tuition Apply Successfully</h4>

<h5>Thank You For Applying Tuition</h5>

tuitions/templates/contact_page.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


    <div class=" shadow p-3 mb-5 bg-white my-5 rounded-lg" style="border-radius: 50px">
      <div class="row">
        <h1 class="text-center pb-4">Contact Us</h1>
        <hr>
        <div class="col-12 col-md-6">
          <img style="width: 100%;" class="mt-5" src="{% static 'img/Contact.png' %}" alt="image">
        </div>
        <div class="col-12 col-md-6">
          <form method="post" class="mt-2 signup-form-style" novalidate>
            <br>
            {% csrf_token %}
            <!-- {{form | crispy }} -->
            {% for fm in form%} {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} {% endfor %}
            <br />
            <button class="btn btn-primary w-100 rounded-pill" type="submit">Submit</button>
            <br />
          </form>
        </div>
      </div>
    </div>


{% comment %} <div class="card m-2">
    <div class="card-body w-50">
        <form method="post">
            <h1>Contact Us</h1>
            {% csrf_token %} {{ form | crispy }}
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>
</div> {% endcomment %}

{% endblock %}

tuitions/templates/review_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class=" back_style">
    <div class=" shadow p-3 mb-5 bg-white my-5 rounded-lg" style="border-radius: 50px">
      <div class="row">
        <h1 class="text-center pb-4">Student Review</h1>
        <hr>
        <form method="post" class="mt-2 profiles-form-style" novalidate>
            <form method="post">
                {% csrf_token %} {{ comment_form | crispy }}
                <button class="btn btn-primary rounded-pill mt-3">Submit</button>
            </form>
        </form>
      </div>
    </div>
  </div>
{% comment %} <div class="card m-2">
    <div class="card-body">
        <form method="post">
            <h1>Student Review</h1>
            {% csrf_token %} {{ comment_form | crispy }}
            <button class="btn btn-warning">Submit</button>
        </form>
    </div>
</div> {% endcomment %}

{% endblock %}

tuitions/templates/tuition_app.html
{% extends "base.html" %}
{% block content %}

<h2>Your Tuition Applications:</h2>
{% if user.tuitionapplication_set.all %}
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Tuition id</th>
        <th scope="col">Apply Tuition Subjects</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for application in user.tuitionapplication_set.all %}
        <tr>
          <th scope="row">{{ application.tuition.id }}</th>
          <td><b>{{ application.tuition.subject_name }}</b></td>
          <td><b>{{ application.status }}</b></td>
          <td>
            {% if application.status == 'approved' %}
              <a class="btn btn-success" href="{% url 'review' application.tuition.id %}">Review Tuition</a>
              {% elif application.status == 'rejected' %}
              <a class="btn btn-danger" href="">Rejected</a>
              {% else %}
              <a class="btn btn-warning" href="">Pending</a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock  %}

tuitions/templates/tuition_details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="d-flex justify-content-between align-items-center mt-3">
      <div class="col-10 col-sm-6 col-md-4">
        <div class="card" style="min-height:500px" >
          <div class="card-body text-center" >
            <img class="img-fluid" style="" src="{{tuition_details.image.url}}" alt="Card image cap">
          </div>
        </div>
      </div>
      
      <div class="col-10 col-sm-6 col-md-4 ">
        <div class="card" style="min-height:500px" >
          <div class="card-body" >
          <h4 class="card-title">Name : {{ tuition_details.teacher_name }}</h4> <br>
          <p class="text-dark"> <b>Subject Name :</b> {{ tuition_details.subject_name }}</p>
          <p class="text-dark"> <b>Location</b> : {{tuition_details.location }}</p>
          <p class="text-dark"> <b>Days</b> : {{tuition_details.tuition_days }}  days/week</p>
          <p class="text-dark"> <b>Salary</b> : TK. {{tuition_details.salary }} (Per Month)</p>
          <br>
          {% if tuition_details.is_available %}
          <h5 class="btn btn-success">Tuitions Available</h5>
          {% else %}
          <h5 class="btn btn-danger w-75">Tuitions Not Available</h5>
          {% endif %}
          <br>
          <br>
          {% if user.is_authenticated %}
            <h6><a href="{% url 'tuition_request' tuition_details.id %}" class=" btn btn-primary w-50 rounded-pill">Apply Tuition</a></h6>
          {% else %}
            <h6><a href="{% url 'login' %}" class=" btn btn-primary w-50 rounded-pill">Apply Tuition</a></h6>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="col-2"></div>


<div class="card mt-5">
    <h3 class="p-3 text-center">Total Review : {{comments | length}}</h3>
    {% for com in comments %}
    <div class="card-body border border-3 m-2 rounded-pill text-center">
      <p><b>{{com.name}}</b> {{com.created_on}}</p>
      <p>{{com.body}}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

tuitions/templates/tuition_request.html
{% extends "base.html" %}
{% block content %}
<h1>Tuition request page</h1>
{% endblock  %}